name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run type-check
      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium
      - run: npm run e2e

  wsl:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v7
      - uses: Vampire/setup-wsl@v7
        with:
          distribution: Ubuntu-24.04
          set-as-default: true
          wsl-version: 2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: Check WSL2
        shell: bash
        run: |
          wsl.exe --status
          if [ $? -ne 0 ]; then
            echo 'WSL2 is not available on this runner'
            exit 1
          fi
      - run: npm run test:wsl
      - run: npm run build
      - name: Install Playwright browser
        run: npx playwright install chromium
      - run: npm run e2e
